route:
  group_by: ['alertname','job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers: discord
  - name: 'discord'
    webhook_configs:
      - url: https://discord.com/api/webhooks/1212739640776466442/dTHmdFXi70RqH3QhOK0i9i2RfvBJOxRlawDjHCQqnAlZ07Dc0fatgV6TXNVWOHFmNPTW


